import 'package:flutter/material.dart';

class EmojiToIcon {
  static IconData getIcon(String iconKey) {
    return switch (iconKey) {
      'cash' || r'$money' || 'dollar' => Icons.attach_money_rounded,
      'bank' => Icons.account_balance_rounded,
      'card' => Icons.credit_card_rounded,
      'atm' => Icons.atm_rounded,
      'coin' || 'crypto' => Icons.currency_bitcoin_rounded,
      'chart' => Icons.bar_chart_rounded,
      'trending_up' => Icons.trending_up_rounded,
      'trending_down' => Icons.trending_down_rounded,
      'restaurant' || 'pizza' => Icons.restaurant_rounded,
      'coffee' => Icons.local_cafe_rounded,
      'bar' => Icons.local_bar_rounded,
      'car' => Icons.directions_car_rounded,
      'flight' => Icons.flight_rounded,
      'bus' => Icons.directions_bus_rounded,
      'taxi' => Icons.local_taxi_rounded,
      'train' => Icons.train_rounded,
      'home' => Icons.home_rounded,
      'cabin' => Icons.cabin_rounded,
      'apartment' => Icons.apartment_rounded,
      'shopping' => Icons.shopping_bag_rounded,
      'cart' => Icons.shopping_cart_rounded,
      'utilities' => Icons.lightbulb_rounded,
      'water' => Icons.water_drop_rounded,
      'bolt' => Icons.bolt_rounded,
      'medical' => Icons.local_hospital_rounded,
      'medicine' => Icons.medical_services_rounded,
      'health' => Icons.health_and_safety_rounded,
      'gaming' => Icons.sports_esports_rounded,
      'books' => Icons.library_books_rounded,
      'movie' => Icons.movie_rounded,
      'music' => Icons.music_note_rounded,
      'work' => Icons.work_rounded,
      'computer' => Icons.computer_rounded,
      'phone' => Icons.phone_iphone_rounded,
      'fitness' => Icons.fitness_center_rounded,
      'soccer' => Icons.sports_soccer_rounded,
      'run' => Icons.directions_run_rounded,
      'wellness' => Icons.spa_rounded,
      'beauty' => Icons.brush_rounded,
      'haircut' => Icons.content_cut_rounded,
      'pets' => Icons.pets_rounded,
      'fuel' => Icons.local_gas_station_rounded,
      'gift' => Icons.card_giftcard_rounded,
      'celebration' => Icons.celebration_rounded,
      'internet' => Icons.language_rounded,
      'cast' => Icons.cast_rounded,
      'school' => Icons.school_rounded,
      'award' => Icons.emoji_events_rounded,
      'lock' => Icons.lock_rounded,
      'transfer' || 'refresh' => Icons.refresh_rounded,
      'target' => Icons.track_changes_rounded,
      'check' => Icons.check_circle_rounded,
      'warning' => Icons.warning_rounded,
      'cancel' => Icons.cancel_rounded,
      'box' => Icons.inventory_2_rounded,
      'assignment' => Icons.assignment_rounded,
      _ => _getLegacyIcon(iconKey),
    };
  }

  static IconData _getLegacyIcon(String iconKey) {
    return switch (iconKey) {
      '\u{1F4B0}' ||
      '\u{1F4B5}' ||
      '\u{1F4B4}' ||
      '\u{1F4B6}' ||
      '\u{1F4B7}' => Icons.attach_money_rounded,
      '\u{1F3E6}' => Icons.account_balance_rounded,
      '\u{1F4B3}' => Icons.credit_card_rounded,
      '\u{1F3E7}' => Icons.atm_rounded,
      '\u{1FA99}' => Icons.currency_bitcoin_rounded,
      '\u{1F4CA}' => Icons.bar_chart_rounded,
      '\u{1F4C8}' => Icons.trending_up_rounded,
      '\u{1F4C9}' => Icons.trending_down_rounded,
      '\u{1F354}' || '\u{1F355}' || '\u{1F35C}' => Icons.restaurant_rounded,
      '\u{2615}' => Icons.local_cafe_rounded,
      '\u{1F377}' => Icons.local_bar_rounded,
      '\u{1F697}' => Icons.directions_car_rounded,
      '\u{2708}\u{FE0F}' => Icons.flight_rounded,
      '\u{1F68C}' => Icons.directions_bus_rounded,
      '\u{1F695}' => Icons.local_taxi_rounded,
      '\u{1F686}' => Icons.train_rounded,
      '\u{1F3E0}' => Icons.home_rounded,
      '\u{1F3E1}' => Icons.cabin_rounded,
      '\u{1F3E2}' => Icons.apartment_rounded,
      '\u{1F6CD}\u{FE0F}' => Icons.shopping_bag_rounded,
      '\u{1F6D2}' => Icons.shopping_cart_rounded,
      '\u{1F4A1}' => Icons.lightbulb_rounded,
      '\u{1F4A7}' => Icons.water_drop_rounded,
      '\u{26A1}' => Icons.bolt_rounded,
      '\u{1F3E5}' => Icons.local_hospital_rounded,
      '\u{1F48A}' => Icons.medical_services_rounded,
      '\u{1FA7A}' => Icons.health_and_safety_rounded,
      '\u{1F3AE}' => Icons.sports_esports_rounded,
      '\u{1F4DA}' || '\u{1F4D6}' => Icons.library_books_rounded,
      '\u{1F3AC}' => Icons.movie_rounded,
      '\u{1F3B5}' || '\u{1F3B8}' => Icons.music_note_rounded,
      '\u{1F4BC}' => Icons.work_rounded,
      '\u{1F4BB}' => Icons.computer_rounded,
      '\u{1F4F1}' => Icons.phone_iphone_rounded,
      '\u{1F3CB}\u{FE0F}' => Icons.fitness_center_rounded,
      '\u{26BD}' => Icons.sports_soccer_rounded,
      '\u{1F3C3}' => Icons.directions_run_rounded,
      '\u{1F9D8}' => Icons.spa_rounded,
      '\u{1F484}' => Icons.brush_rounded,
      '\u{1F487}' => Icons.content_cut_rounded,
      '\u{1F43E}' || '\u{1F415}' || '\u{1F408}' => Icons.pets_rounded,
      '\u{26FD}' => Icons.local_gas_station_rounded,
      '\u{1F381}' => Icons.card_giftcard_rounded,
      '\u{1F389}' => Icons.celebration_rounded,
      '\u{1F310}' => Icons.language_rounded,
      '\u{1F4E1}' => Icons.cast_rounded,
      '\u{1F393}' => Icons.school_rounded,
      '\u{1F947}' || '\u{1F948}' => Icons.emoji_events_rounded,
      '\u{1F512}' => Icons.lock_rounded,
      '\u{1F504}' => Icons.refresh_rounded,
      '\u{1F3AF}' => Icons.track_changes_rounded,
      '\u{2705}' => Icons.check_circle_rounded,
      '\u{26A0}\u{FE0F}' => Icons.warning_rounded,
      '\u{274C}' => Icons.cancel_rounded,
      '\u{1F4E6}' => Icons.inventory_2_rounded,
      _ => Icons.category_rounded,
    };
  }

  static String getLabel(String iconKey) {
    return switch (iconKey) {
      'cash' || 'dollar' || r'$money' => 'Cash',
      'bank' => 'Bank',
      'card' => 'Card',
      'chart' => 'Chart',
      'trending_up' => 'Up',
      'trending_down' => 'Down',
      'restaurant' || 'pizza' => 'Food',
      'coffee' => 'Coffee',
      'car' => 'Car',
      'flight' => 'Flight',
      'home' => 'Home',
      'shopping' => 'Shopping',
      'utilities' => 'Utilities',
      'medical' => 'Medical',
      'gaming' => 'Entertainment',
      'books' => 'Education',
      'work' => 'Work',
      'computer' => 'Tech',
      'fitness' => 'Fitness',
      'beauty' => 'Beauty',
      'pets' => 'Pets',
      'fuel' => 'Gas',
      'gift' => 'Gifts',
      'internet' => 'Internet',
      'box' => 'Other',
      _ => 'Category',
    };
  }
}
